#!/usr/bin/env bash
# AUTOGENERATED by /ark-onboard — do not hand-edit.
# Ensures the project repo has a `vault` symlink to the centralized vault repo.
# Called by .git/hooks/post-checkout on every branch checkout / worktree add.
# Also called by .superset/config.json setup hook if the project uses superset.
set -e
VAULT_TARGET="$HOME/.superset/vaults/ark-trade-agent"
TINYAGI_FALLBACK=""   # may be empty; populated only if the project declares a tinyAGI deploy

# 1. Existing valid symlink -> done.
if [ -L vault ] && [ -e vault ]; then
  exit 0
fi
# 2. Broken symlink -> remove it and continue.
if [ -L vault ] && [ ! -e vault ]; then
  rm vault
fi
# 3. Real directory -> loud failure; indicates unfinished migration.
if [ -d vault ]; then
  echo "ERROR: vault/ is a real directory. Run /ark-onboard to externalize." >&2
  exit 1
fi
# 4. Centralized target exists -> link.
if [ -d "$VAULT_TARGET" ]; then
  ln -s "$VAULT_TARGET" vault
  echo "vault symlink created -> $VAULT_TARGET"
  exit 0
fi
# 5. TinyAGI fallback exists -> link.
if [ -n "$TINYAGI_FALLBACK" ] && [ -d "$TINYAGI_FALLBACK" ]; then
  ln -s "$TINYAGI_FALLBACK" vault
  echo "vault symlink created (tinyagi fallback) -> $TINYAGI_FALLBACK"
  exit 0
fi
# 6. Nothing found -> clone instructions.
echo "ERROR: vault repo not cloned. Clone the vault repo to $VAULT_TARGET, then retry." >&2
exit 1
